"""initial schema

Revision ID: 80dfde265721
Revises: 
Create Date: 2026-09-15 10:06:26.449072

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80dfde265721'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('country_shipping_rules',
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.Column('base_fee_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_kg_fee_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customs_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_days_min', sa.Integer(), nullable=False),
    sa.Column('estimated_days_max', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_shipping_rules_country_code'), 'country_shipping_rules', ['country_code'], unique=True)
    op.create_table('discount_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('PERCENT', 'FIXED', name='discount_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_codes_code'), 'discount_codes', ['code'], unique=True)
    op.create_table('hair_colors',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hex_swatch', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hair_lengths',
    sa.Column('inches', sa.Integer(), nullable=False),
    sa.Column('cm', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inches')
    )
    op.create_table('pricing_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('shipping_per_kg_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('packaging_fee_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kes_adjustment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'SUPPLIER', 'CUSTOMER', name='user_role'), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('addresses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('line1', sa.String(), nullable=False),
    sa.Column('line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('carts',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_token', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_carts_guest_token'), 'carts', ['guest_token'], unique=True)
    op.create_table('exchange_rates',
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('target_currency', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'target_currency')
    )
    op.create_table('orders',
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PAID', 'SENT_TO_SUPPLIER', 'SUPPLIER_PROCESSING', 'READY_FOR_PICKUP', 'RECEIVED_AT_OFFICE', 'SHIPPED_INTERNATIONALLY', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('subtotal_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_fee_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('handling_fee_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customs_estimate_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_code_id', sa.UUID(), nullable=True),
    sa.Column('total_amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exchange_rate_applied', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_amount_kes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipping_country', sa.String(length=2), nullable=False),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('whatsapp_number', sa.String(), nullable=False),
    sa.Column('default_margin_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('order_status_history',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING_PAYMENT', 'PAID', 'SENT_TO_SUPPLIER', 'SUPPLIER_PROCESSING', 'READY_FOR_PICKUP', 'RECEIVED_AT_OFFICE', 'SHIPPED_INTERNATIONALLY', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='order_status'), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING_PAYMENT', 'PAID', 'SENT_TO_SUPPLIER', 'SUPPLIER_PROCESSING', 'READY_FOR_PICKUP', 'RECEIVED_AT_OFFICE', 'SHIPPED_INTERNATIONALLY', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('MPESA', 'BANK_TRANSFER', name='payment_provider_type'), nullable=False),
    sa.Column('provider_ref', sa.String(), nullable=True),
    sa.Column('amount_kes', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('raw_callback_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proof_of_payment_url', sa.String(), nullable=True),
    sa.Column('confirmed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_provider_ref'), 'payments', ['provider_ref'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hair_length', sa.String(), nullable=True),
    sa.Column('texture', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('accessory_type', sa.String(), nullable=True),
    sa.Column('country_of_origin', sa.String(), nullable=False),
    sa.Column('processing_time_days', sa.Integer(), nullable=False),
    sa.Column('base_price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_weight_grams', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='product_status'), nullable=False),
    sa.Column('hair_category', sa.Enum('BULK_HAIR', 'EXTENSION', 'WIG', 'CLOSURE', 'FRONTAL', 'MACHINE_WEFT', name='hair_category'), nullable=False),
    sa.Column('drawn_type', sa.Enum('SINGLE_DRAWN', 'DOUBLE_DRAWN', 'SUPER_DOUBLE_DRAWN', name='drawn_type'), nullable=True),
    sa.Column('texture_category', sa.Enum('STRAIGHT', 'WAVY', 'CURLY', name='texture_category'), nullable=True),
    sa.Column('attachment_type', sa.Enum('SILK', 'TAPE', 'CLIP_IN', 'PONYTAIL', 'NANO_RING', name='attachment_type'), nullable=True),
    sa.Column('tip_type', sa.Enum('I_TIP', 'U_TIP', 'FLAT_TIP', 'V_TIP', name='tip_type'), nullable=True),
    sa.Column('wig_construction', sa.Enum('LACE_FRONT', 'FULL_LACE', 'CLOSURE_WIG', 'U_PART', 'GLUELESS', name='wig_construction'), nullable=True),
    sa.Column('wig_cap_size', sa.String(), nullable=True),
    sa.Column('wig_features', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('returns',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'REFUNDED', name='return_status'), nullable=False),
    sa.Column('refund_amount_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=False),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('origin_office_location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.create_table('supplier_orders',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'ACKNOWLEDGED', 'IN_PRODUCTION', 'READY', 'DECLINED', name='supplier_order_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_days', sa.Integer(), nullable=True),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variants',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('length_inches', sa.Integer(), nullable=True),
    sa.Column('density', sa.String(), nullable=True),
    sa.Column('texture', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('price_delta_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False),
    sa.Column('weight_override_grams', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('reviews',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='review_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_milestones',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('carrier_event_id', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_usd_at_purchase', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('cloudinary_public_id', sa.String(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_images')
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('shipment_milestones')
    op.drop_table('reviews')
    op.drop_table('product_variants')
    op.drop_table('supplier_orders')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('returns')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_payments_provider_ref'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('order_status_history')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_carts_guest_token'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('pricing_settings')
    op.drop_table('hair_lengths')
    op.drop_table('hair_colors')
    op.drop_index(op.f('ix_discount_codes_code'), table_name='discount_codes')
    op.drop_table('discount_codes')
    op.drop_index(op.f('ix_country_shipping_rules_country_code'), table_name='country_shipping_rules')
    op.drop_table('country_shipping_rules')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
