"""add package notes column

Revision ID: a9491cf1a36b
Revises: 797d302acfa3
Create Date: 2026-09-16 10:55:44.107343

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a9491cf1a36b'
down_revision: str | None = '797d302acfa3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'notes')
    # ### end Alembic commands ###
