"""add warehouse external shipments packages consolidation customs exceptions order tracking number

Revision ID: be6f2c3535f6
Revises: 80dfde265721
Create Date: 2026-09-16 09:30:15.450522

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be6f2c3535f6'
down_revision: str | None = '80dfde265721'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('VN', 'KE', name='warehouse_type'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_table('consolidations',
    sa.Column('consolidation_code', sa.String(), nullable=False),
    sa.Column('origin_warehouse_id', sa.UUID(), nullable=False),
    sa.Column('destination_warehouse_id', sa.UUID(), nullable=True),
    sa.Column('freight_method', sa.String(), nullable=True),
    sa.Column('freight_provider', sa.String(), nullable=True),
    sa.Column('total_weight_grams', sa.Integer(), nullable=False),
    sa.Column('total_volume_cbm', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('declared_value_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'READY_FOR_EXPORT', 'DEPARTED', 'IN_TRANSIT', 'ARRIVED', 'CLOSED', name='consolidation_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['origin_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consolidations_consolidation_code'), 'consolidations', ['consolidation_code'], unique=True)
    op.create_table('external_shipments',
    sa.Column('tracking_number', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('supplier_reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', name='external_shipment_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_shipments_tracking_number'), 'external_shipments', ['tracking_number'], unique=True)
    op.create_table('ops_exceptions',
    sa.Column('type', sa.Enum('SUPPLIER_DELAYED', 'SUPPLIER_FAILED_TO_DISPATCH', 'PACKAGE_MISSING', 'PACKAGE_DAMAGED', 'WRONG_PACKAGE', 'WEIGHT_MISMATCH', 'PRODUCT_MISMATCH', 'QC_FAILURE', 'SHIPMENT_DELAYED', 'CUSTOMS_QUERY', 'CUSTOMS_HOLD', 'CUSTOMS_ISSUE', 'DELIVERY_FAILED', 'CUSTOMER_UNAVAILABLE', 'WRONG_ADDRESS', 'PAYMENT_ISSUE', 'RETURNED_SHIPMENT', name='ops_exception_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ops_exception_severity'), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='ops_exception_status'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_exceptions_entity_id'), 'ops_exceptions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_ops_exceptions_entity_type'), 'ops_exceptions', ['entity_type'], unique=False)
    op.create_table('packages',
    sa.Column('package_code', sa.String(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('external_shipment_id', sa.UUID(), nullable=True),
    sa.Column('supplier_order_id', sa.UUID(), nullable=True),
    sa.Column('warehouse_id', sa.UUID(), nullable=True),
    sa.Column('consolidation_id', sa.UUID(), nullable=True),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('length_cm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('width_cm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('volume_cbm', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('qc_status', sa.Enum('PENDING', 'PASSED', 'FAILED', name='package_qc_status'), nullable=False),
    sa.Column('condition', sa.Enum('GOOD', 'DAMAGED', name='package_condition'), nullable=True),
    sa.Column('photo_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_code', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('EXPECTED', 'RECEIVED', 'READY_FOR_CONSOLIDATION', 'CONSOLIDATED', 'IN_TRANSIT', 'AT_CUSTOMS_KENYA', 'READY_FOR_DELIVERY', 'DELIVERED', 'EXCEPTION', name='package_status'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.Column('label_printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label_reprint_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(order_id IS NOT NULL AND external_shipment_id IS NULL) OR (order_id IS NULL AND external_shipment_id IS NOT NULL)', name='ck_packages_exactly_one_owner'),
    sa.ForeignKeyConstraint(['consolidation_id'], ['consolidations.id'], ),
    sa.ForeignKeyConstraint(['external_shipment_id'], ['external_shipments.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_order_id'], ['supplier_orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_package_code'), 'packages', ['package_code'], unique=True)
    op.create_table('customs_declarations',
    sa.Column('consolidation_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('hs_code', sa.String(), nullable=True),
    sa.Column('declared_value_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duty_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PREPARING', 'DECLARED', 'QUERY_RAISED', 'CLEARED', name='customs_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('consolidation_id IS NOT NULL OR package_id IS NOT NULL', name='ck_customs_declarations_has_owner'),
    sa.ForeignKeyConstraint(['consolidation_id'], ['consolidations.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_tracking_number'), 'orders', ['tracking_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_tracking_number'), table_name='orders')
    op.drop_column('orders', 'tracking_number')
    op.drop_table('customs_declarations')
    op.drop_index(op.f('ix_packages_package_code'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_ops_exceptions_entity_type'), table_name='ops_exceptions')
    op.drop_index(op.f('ix_ops_exceptions_entity_id'), table_name='ops_exceptions')
    op.drop_table('ops_exceptions')
    op.drop_index(op.f('ix_external_shipments_tracking_number'), table_name='external_shipments')
    op.drop_table('external_shipments')
    op.drop_index(op.f('ix_consolidations_consolidation_code'), table_name='consolidations')
    op.drop_table('consolidations')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###

    # Not auto-generated: autogenerate's drop_table calls above leave the
    # native Postgres ENUM types behind, which breaks a subsequent upgrade
    # ("type already exists"). Drop them explicitly, after every column that
    # used them has already been dropped above.
    bind = op.get_bind()
    for enum_name in (
        'customs_status',
        'package_status',
        'package_condition',
        'package_qc_status',
        'ops_exception_status',
        'ops_exception_severity',
        'ops_exception_type',
        'external_shipment_status',
        'consolidation_status',
        'warehouse_type',
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
