"""add homepage banners and product placements, extend categories

Revision ID: cc745216339c
Revises: d62ba7684e42
Create Date: 2026-09-16 20:21:47.725029

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc745216339c'
down_revision: str | None = 'd62ba7684e42'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_banners',
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('subheadline', sa.Text(), nullable=True),
    sa.Column('cta_label', sa.String(), nullable=True),
    sa.Column('cta_url', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage_product_placements',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.Enum('FEATURED', 'DEAL', name='homepage_placement_section'), nullable=False),
    sa.Column('sale_price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('categories', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    # server_default backfills existing rows for these NOT NULL columns -
    # the model's Python-level default=False/0 only applies to new ORM
    # inserts, not to ALTER TABLE ADD COLUMN against existing rows.
    op.add_column('categories', sa.Column('is_featured', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('categories', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'sort_order')
    op.drop_column('categories', 'is_featured')
    op.drop_column('categories', 'cloudinary_public_id')
    op.drop_column('categories', 'image_url')
    op.drop_table('homepage_product_placements')
    op.drop_table('homepage_banners')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop enum TYPE objects on its own - see
    # docs/VNKE_ROADMAP.md Phase 2 for why this repo's own migrations always
    # do it explicitly.
    postgresql.ENUM(name='homepage_placement_section').drop(op.get_bind(), checkfirst=True)
