"""retire legacy shipment model, add tracking events and shipment fields on consolidation

Revision ID: d62ba7684e42
Revises: 23d548b7b448
Create Date: 2026-09-16 14:40:20.142821

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd62ba7684e42'
down_revision: str | None = '23d548b7b448'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_events',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('external_shipment_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('order_id IS NOT NULL OR external_shipment_id IS NOT NULL OR package_id IS NOT NULL', name='ck_tracking_events_has_owner'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['external_shipment_id'], ['external_shipments.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shipment_milestones')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_table('shipments')
    op.add_column('consolidations', sa.Column('shipment_code', sa.String(), nullable=True))
    op.add_column('consolidations', sa.Column('carrier', sa.String(), nullable=True))
    op.add_column('consolidations', sa.Column('carrier_tracking_reference', sa.String(), nullable=True))
    op.add_column('consolidations', sa.Column('current_location', sa.String(), nullable=True))
    op.add_column('consolidations', sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_consolidations_shipment_code'), 'consolidations', ['shipment_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consolidations_shipment_code'), table_name='consolidations')
    op.drop_column('consolidations', 'estimated_arrival')
    op.drop_column('consolidations', 'current_location')
    op.drop_column('consolidations', 'carrier_tracking_reference')
    op.drop_column('consolidations', 'carrier')
    op.drop_column('consolidations', 'shipment_code')
    op.create_table('shipments',
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tracking_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('carrier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('origin_office_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('shipments_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shipments_pkey')),
    sa.UniqueConstraint('order_id', name=op.f('shipments_order_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    op.create_table('shipment_milestones',
    sa.Column('shipment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('carrier_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('shipment_milestones_created_by_id_fkey')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('shipment_milestones_shipment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shipment_milestones_pkey'))
    )
    op.drop_table('tracking_events')
    # ### end Alembic commands ###
